### ISSUE TITLE
Cannot find module 'llama-pack/dist/lib/TwaGenerator'

### ISSUE THREAD

**Issue by davidmaxwaterman** [pwa-builder/CloudAPK#9]
I'm getting the problem below and can't seem to get past it. Any pointers appreciated.

```
CloudAPK$ docker run -p 3000:80 --name cloudapk cloudapk-image

> cloudapk@1.0.0 start /app
> node server.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'llama-pack/dist/lib/TwaGenerator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/build/llamaPackWrapper.js:6:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cloudapk@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cloudapk@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-20T06_07_46_967Z-debug.log
```

ubuntu 19.10 - cloned this repo - current commit is a23698ed6a0e75160bc2f5d8a34ab339c0e414f9

**Comment by JudahGabriel** [comment]
Might be related to the new llama-pack, which split into 2 packages: core and CLI. This makes llama-pack/dist/lib/TwaGenerator no longer resolve.

We just [pushed new code](https://github.com/pwa-builder/CloudAPK/commit/a8ea8690e35d595bb862c62f3efd7df8949e07e2) to update to the latest llama-pack. Give it a try?

**Comment by davidmaxwaterman** [comment]
I think it's doing something now, so I just need to figure out what to do next :) In any case, this is surely fixed - thanks!
